export type Language = "en" | "kh";

export const translations = {
  en: {
    brand: "Sabai Academy",
    tagline: "Unlocking Potential with Modern Digital Skills",
    home: "Home",
    courses: "Courses",
    about: "About & FAQs",
    dashboard: "My Dashboard",
    adminPanel: "Admin Panel",
    login: "Log In",
    register: "Sign Up",
    logout: "Log Out",
    welcomeBack: "Welcome back",
    points: "Points",
    level: "Level",
    allCategories: "All Categories",
    searchPlaceholder: "Search courses, React, AI marketing...",
    filterCategory: "Filter by Category",
    sortBy: "Sort By",
    priceLowHigh: "Price: Low to High",
    priceHighLow: "Price: High to Low",
    popular: "Popularity",
    hours: "hours",
    lessons: "lessons",
    duration: "Duration",
    instructor: "Instructor",
    category: "Category",
    rating: "Rating",
    buyNow: "Buy Now",
    enrollNow: "Enroll Now",
    discount: "Promo discount",
    originalPrice: "Price",
    inclusiveCoupon: "Coupon (SABAI20 for 20% off):",
    apply: "Apply",
    couponApplied: "Coupon applied! Enjoy 20% savings.",
    checkoutTitle: "Choose Payment Method",
    cambodiaBank: "Cambodia Bank Transfer (QR Code Auto-scan)",
    payDescription: "Scan the official ABA, ACLEDA, or Wing KHQR code below and transfer the amount. Upload your transaction receipt screenshot to complete activation.",
    uploadReceipt: "Upload Payment Screenshot",
    submitConfirmation: "Submit Proof of Payment",
    uploadSuccess: "Payment receipt sent! Administrator will verify and unlock your course shortly.",
    freeUnlockSuccess: "Course successfully enrolled!",
    continueLearning: "Continue Learning",
    myCourses: "My Enrolled Courses",
    noCoursesJoined: "You haven't enrolled in any courses yet.",
    certificate: "Certificate",
    downloadCert: "Download Certificate",
    milestonesTitle: "Course Milestones",
    nextLesson: "Next Lesson",
    prevLesson: "Previous Lesson",
    quizTitle: "Interactive Lesson Quiz",
    submitQuiz: "Submit Answers",
    quizPassed: "Passed! You unlocked +5 studying points.",
    quizFailed: "No match. Review the lesson details and try again.",
    aiTopicPlaceholder: "E.g. Advanced Docker for Creators, NextJS ActionStates...",
    askAiTitle: "Kru Sabai AI Assistant",
    aiDescription: "Ask questions, explore curriculum recommendations, or request coding tutorials instantly.",
    aiPlaceholder: "Type your code or learning query here...",
    send: "Send",
    adminDashboard: "Admin Metrics Dashboard",
    totalSales: "Total Collections",
    totalUsers: "Registered Accounts",
    activeStudents: "Students Learning",
    pendingVerifications: "Pending Payments Verification",
    approve: "Approve",
    decline: "Decline",
    userRole: "Role",
    status: "Status",
    actions: "Actions",
    logsTitle: "LMS Telemetry Activity Logs",
    faqTitle: "Frequently Asked Questions",
    contactUs: "Contact Support",
    blogTitle: "Sabai Tech Insights",
    footerQuote: "Empowering Next-Generation Digital Talents in Cambodia",
    by: "by",
    khmerLogoSubtitle: "ស្ថាបនាអនាគតបច្ចេកវិទ្យា"
  },
  kh: {
    brand: "សាបាយ អាខាដឺមី (Sabai Academy)",
    tagline: "អភិវឌ្ឍន៍ជំនាញឌីជីថលទំនើប ជាមួយសាស្ត្រាចារ្យជំនាញ",
    home: "ទំព័រដើម",
    courses: "វគ្គសិក្សា",
    about: "អំពីយើង និង សំណួរញឹកញាប់",
    dashboard: "គណនីសិក្សា",
    adminPanel: "ផ្ទាំងគ្រប់គ្រង",
    login: "ចូលគណនី",
    register: "ចុះឈ្មោះសិក្សា",
    logout: "ចាកចេញ",
    welcomeBack: "សូមស្វាគមន៍មកវិញ",
    points: "ពិន្ទុសន្សំ",
    level: "កម្រិតយល់ដឹង",
    allCategories: "គ្រប់មុខជំនាញ",
    searchPlaceholder: "ស្វែងរកវគ្គសិក្សា, React, AI Marketing...",
    filterCategory: "ជ្រើសរើសប្រភេទ",
    sortBy: "តម្រៀបតាម",
    priceLowHigh: "តម្លៃ៖ ទាបទៅខ្ពស់",
    priceHighLow: "តម្លៃ៖ ខ្ពស់ទៅទាប",
    popular: "ភាពពេញនិយមបំផុត",
    hours: "ម៉ោងសិក្សា",
    lessons: "មេរៀនសរុប",
    duration: "រយៈពេល",
    instructor: "សាស្ត្រចារ្យ",
    category: "ប្រភេទ",
    rating: "ការវាយតម្លៃ",
    buyNow: "ទិញវគ្គសិក្សានេះ",
    enrollNow: "ចុះឈ្មោះរៀនភ្លាមៗ",
    discount: "ប្រូម៉ូសិនដកសេវា",
    originalPrice: "តម្លៃដើម",
    inclusiveCoupon: "លេខកូដបញ្ចុះតម្លៃ (SABAI20 កាត់ ២០%)៖",
    apply: "បញ្ចូល",
    couponApplied: "អនុវត្តកូដជោគជ័យ! ទទួលបានការដកសេវា ២០%។",
    checkoutTitle: "ជ្រើសរើសវិធីសាស្ត្រទូទាត់ប្រាក់",
    cambodiaBank: "ផ្ទេរប្រាក់តាមធនាគារក្នុងស្រុក (KHQR ស្វ័យប្រវត្តិ)",
    payDescription: "សូមស្កែន QR កូដផ្លូវការធនាគារ ABA, ACLEDA ឬ Wing ខាងក្រោមដើម្បីបញ្ជូនទូទាត់។ បន្ទាប់មក សូមបញ្ចូលរូបភាព Screenshot វិក្កយបត្រ ដើម្បីឲ្យប្រព័ន្ធបើកវគ្គសិក្សាជូន។",
    uploadReceipt: "បញ្ចូលរូបវិក្កយបត្រ (Screenshot)",
    submitConfirmation: "បញ្ជាក់ការទូទាត់ប្រាក់",
    uploadSuccess: "វិក្កយបត្រត្រូវបានផ្ញើជូនជោគជ័យ! ប្រព័ន្ធរង់ចាំការផ្ទៀងផ្ទាត់រូបវិក្កយបត្រ ហើយនឹងបើកវគ្គសិក្សាជូនលោកអ្នកក្នុងពេលឆាប់ៗ។",
    freeUnlockSuccess: "ចុះឈ្មោះសិក្សាដោយជោគជ័យ!",
    continueLearning: "ចូលទៅរៀនបន្ត",
    myCourses: "វគ្គសិក្សាដែលខ្ញុំបានចូលរួម",
    noCoursesJoined: "លោកអ្នកមិនទាន់មានវគ្គសិក្សាក្នុងគណនីនៅឡើយទេ។",
    certificate: "វិញ្ញាបនបត្រ",
    downloadCert: "ទាញយកវិញ្ញាបនបត្រផ្លូវការ",
    milestonesTitle: "ដំណើរការសិក្សារបស់ខ្ញុំ",
    nextLesson: "មេរៀនបន្ទាប់",
    prevLesson: "មេរៀនមុន",
    quizTitle: "តេស្តវាស់ស្ទង់សមត្ថភាពមេរៀន",
    submitQuiz: "បញ្ជូនចម្លើយតេស្ត",
    quizPassed: "ប្រលងជាប់! អ្នកទទួលបាន ២០+ ពិន្ទុសិក្សាថ្មី។",
    quizFailed: "ចម្លើយមិនទាន់ត្រឹមត្រូវឡើយ។ សូមត្រួតពិនិត្យមេរៀនឡើងវិញហើយសាកល្បងម្ដងទៀត។",
    aiTopicPlaceholder: "ឧទាហរណ៍៖ ការគ្រប់គ្រង Docker, Dynamic Route, React State...",
    askAiTitle: "ជំនួយការសិក្សា AI (លោកគ្រូសាបាយ)",
    aiDescription: "សួរសំណួរដោះស្រាយកូដ, ប្រឹក្សាយោបល់គម្រោងសិក្សា ឬបង្កើត Outline មេរៀនភ្លាមៗ។",
    aiPlaceholder: "សួរសំណួរ ឬបញ្ហា Code របស់អ្នកនៅទីនេះ...",
    send: "បញ្ជូន",
    adminDashboard: "ផ្ទាំងគ្រប់គ្រងទិន្នន័យទូទៅ (Metrics)",
    totalSales: "ចំណូលសរុប ( collections )",
    totalUsers: "គណនីចុះឈ្មោះ",
    activeStudents: "សិស្សសកម្មកំពុងរៀន",
    pendingVerifications: "ការទូទាត់រង់ចាំផ្ទៀងផ្ទាត់",
    approve: "អនុម័តជោគជ័យ",
    decline: "បដិសេធចោល",
    userRole: "តួនាទី",
    status: "ស្ថានភាព",
    actions: "សកម្មភាព",
    logsTitle: "ប្រវត្តិសកម្មភាពសរុបក្នុងប្រព័ន្ធ (Telemetry Logs)",
    faqTitle: "សំណួរដែលសួរញឹកញាប់បំផុត",
    contactUs: "ទាក់ទងមកផ្ទាល់",
    blogTitle: "ស្វែងយល់អត្ថបទបច្ចេកវិទ្យាថ្មីៗ",
    footerQuote: "ចូលរួមស្ថាបនាធនធានបច្ចេកវិទ្យា និងអ្នកជំនាញជំនាន់ក្រោយក្នុងប្រទេសកម្ពុជា",
    by: "ដោយ",
    khmerLogoSubtitle: "វិទ្យាស្ថានបណ្តុះបណ្តាលបច្ចេកវិទ្យា"
  }
};

export function getTranslation(lang: Language, key: keyof typeof translations["en"]): string {
  return translations[lang][key] || translations["en"][key] || String(key);
}
